USE KOD;

-- 분기 통계
SELECT 
    SALES_STATISTICS.YEAR AS '년',
    SALES_STATISTICS.QUARTER AS '분기', 
    SALES_STATISTICS.PRODUCT_ID as '상품ID',
    SALES_STATISTICS.PRODUCT_NAME AS '상품명',
    SALES_STATISTICS.PRODUCT_PRICE AS '상품가격',
    SALES_STATISTICS.PRODUCT_SALES_QUANTITY AS '판매수량',
    SALES_STATISTICS.PRODUCT_SALES_REVENUE AS '상품매출',
    QUARTER_AVENUE.QUARTER_AVENUE AS '분기매출'
FROM (
    SELECT 
        YEAR(OL.ORDERLIST_DATE) AS 'YEAR',
        QUARTER(OL.ORDERLIST_DATE) AS 'QUARTER',
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        P.PRODUCT_PRICE,
        SUM(OC.ORDERCONTENT_CNT) AS 'PRODUCT_SALES_QUANTITY',
        SUM(P.PRODUCT_PRICE * OC.ORDERCONTENT_CNT) AS 'PRODUCT_SALES_REVENUE'
    FROM 
        ORDERLIST OL
    JOIN 
        ORDERCONTENT OC ON OL.ORDERLIST_ID = OC.ORDERLIST_ID
    JOIN 
        PRODUCT P ON OC.PRODUCT_ID = P.PRODUCT_ID
    GROUP BY 
        YEAR(OL.ORDERLIST_DATE),
        QUARTER(OL.ORDERLIST_DATE),
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        P.PRODUCT_PRICE
) AS SALES_STATISTICS
JOIN (
    SELECT 
        YEAR(OL.ORDERLIST_DATE) AS 'YEAR',
        QUARTER(OL.ORDERLIST_DATE) AS 'QUARTER',
        SUM(P.PRODUCT_PRICE * OC.ORDERCONTENT_CNT) AS 'QUARTER_AVENUE'
    FROM 
        ORDERLIST OL
    JOIN 
        ORDERCONTENT OC ON OL.ORDERLIST_ID = OC.ORDERLIST_ID
    JOIN 
        PRODUCT P ON OC.PRODUCT_ID = P.PRODUCT_ID
    GROUP BY 
        YEAR(OL.ORDERLIST_DATE),
        QUARTER(OL.ORDERLIST_DATE)
) AS QUARTER_AVENUE ON SALES_STATISTICS.YEAR = QUARTER_AVENUE.YEAR AND SALES_STATISTICS.QUARTER = QUARTER_AVENUE.QUARTER
ORDER BY 
    SALES_STATISTICS.YEAR,
    SALES_STATISTICS.QUARTER,
    SALES_STATISTICS.PRODUCT_SALES_REVENUE DESC;



-- 분기별 상품매출 순위
SELECT 
    YEAR(OL.ORDERLIST_DATE) AS '년',
    QUARTER(OL.ORDERLIST_DATE) AS '분기',
    P.PRODUCT_ID,
    P.PRODUCT_NAME AS '상품명',
    P.PRODUCT_PRICE AS '상품가격',
    SUM(OC.ORDERCONTENT_CNT) AS '판매수량',
    SUM(P.PRODUCT_PRICE * OC.ORDERCONTENT_CNT) AS '상품매출'
FROM 
    kod.ORDERLIST OL
JOIN 
    kod.ORDERCONTENT OC ON OL.ORDERLIST_ID = OC.ORDERLIST_ID
JOIN 
    kod.PRODUCT P ON OC.PRODUCT_ID = P.PRODUCT_ID
GROUP BY 
    YEAR(OL.ORDERLIST_DATE),
    QUARTER(OL.ORDERLIST_DATE),
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.PRODUCT_PRICE
ORDER BY 
    YEAR(OL.ORDERLIST_DATE),
    QUARTER(OL.ORDERLIST_DATE),
    `상품매출` DESC;
    
    
    
-- 년도별 상품매출 순위
SELECT 
    YEAR(OL.ORDERLIST_DATE) AS `년`,
    P.PRODUCT_ID,
    P.PRODUCT_NAME AS '상품명',
    P.PRODUCT_PRICE AS `상품가격`,
    SUM(OC.ORDERCONTENT_CNT) AS `판매수량`,
    SUM(P.PRODUCT_PRICE * OC.ORDERCONTENT_CNT) AS `상품매출 합계`
FROM 
    kod.ORDERLIST OL
JOIN 
    kod.ORDERCONTENT OC ON OL.ORDERLIST_ID = OC.ORDERLIST_ID
JOIN 
    kod.PRODUCT P ON OC.PRODUCT_ID = P.PRODUCT_ID
GROUP BY 
    YEAR(OL.ORDERLIST_DATE),
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.PRODUCT_PRICE
ORDER BY 
    YEAR(OL.ORDERLIST_DATE),
    `상품매출 합계` DESC;
    


-- 일매출 for 30days
SELECT 
    YEAR(ol.ORDERLIST_DATE) AS 년,
    MONTH(ol.ORDERLIST_DATE) AS 월,
    DAY(ol.ORDERLIST_DATE) AS 일,
    SUM(pc.ORDERCONTENT_CNT * p.PRODUCT_PRICE) AS 일매출
FROM 
    ORDERLIST ol
INNER JOIN 
    ORDERCONTENT pc ON ol.ORDERLIST_ID = pc.ORDERLIST_ID
INNER JOIN 
    PRODUCT p ON pc.PRODUCT_ID = p.PRODUCT_ID
WHERE 
    ol.ORDERLIST_DATE >= CURDATE() - INTERVAL 29 DAY 
    AND ol.ORDERLIST_DATE < CURDATE() + INTERVAL 1 DAY
GROUP BY 
    YEAR(ol.ORDERLIST_DATE),
    MONTH(ol.ORDERLIST_DATE),
    DAY(ol.ORDERLIST_DATE);
    
    
    
-- 분기매출 for 2years
SELECT 
    YEAR(ol.ORDERLIST_DATE) AS 년,
    QUARTER(ol.ORDERLIST_DATE) AS 분기,
    SUM(pc.ORDERCONTENT_CNT * p.PRODUCT_PRICE) AS 분기매출
FROM 
    ORDERLIST ol
INNER JOIN 
    ORDERCONTENT pc ON ol.ORDERLIST_ID = pc.ORDERLIST_ID
INNER JOIN 
    PRODUCT p ON pc.PRODUCT_ID = p.PRODUCT_ID
WHERE
    ol.ORDERLIST_DATE >= DATE_SUB(CURDATE(), INTERVAL 2 YEAR)
GROUP BY 
    YEAR(ol.ORDERLIST_DATE),
    QUARTER(ol.ORDERLIST_DATE)
ORDER BY
    YEAR(ol.ORDERLIST_DATE),
    QUARTER(ol.ORDERLIST_DATE);
    
    
    
-- 1년 간의 월매출
SELECT 
    YEAR(ol.ORDERLIST_DATE) AS 년,
    MONTH(ol.ORDERLIST_DATE) AS 월,
    SUM(pc.ORDERCONTENT_CNT * p.PRODUCT_PRICE) AS 월매출
FROM 
    ORDERLIST ol
INNER JOIN 
    ORDERCONTENT pc ON ol.ORDERLIST_ID = pc.ORDERLIST_ID
INNER JOIN 
    PRODUCT p ON pc.PRODUCT_ID = p.PRODUCT_ID
WHERE 
    ol.ORDERLIST_DATE >= DATE_FORMAT(CURDATE() - INTERVAL 11 MONTH, '%Y-%m-01') 
    AND ol.ORDERLIST_DATE < DATE_FORMAT(CURDATE() + INTERVAL 1 MONTH, '%Y-%m-01')
GROUP BY 

    YEAR(ol.ORDERLIST_DATE),
    MONTH(ol.ORDERLIST_DATE);
    

-- 쿠폰코드로 쿠폰조회
SELECT COUPON_ID, 
			 COUPON_CONTENT, 
			 COUPON_DISCOUNT_RATE, 
			 COUPON_NAME, 
			 COUPON_CODE, 
			 COUPON_USE_DATE, 
			 COUPON_TYPE 
			 FROM COUPON 
			 WHERE COUPON_CODE='26TLKRBY1FBPKK3U';
             
-- 등급별 회원조회
SELECT MEMBER_ID,MEMBER_GRADE,MEMBER_NAME FROM MEMBER WHERE MEMBER_GRADE='VIP';
    